export interface EnterpriseSourceSeed {
  name: string;
  nameArabic: string;
  url: string;
  feedUrl: string;
  logo: string;
  country: string;
  language: string;
  category: string;
  type: string;
  enabled: boolean;
  priority: number;
  trustScore: number;
  fetchInterval: number;
}

export const ENTERPRISE_SOURCE_CATALOG: EnterpriseSourceSeed[] = [
  // --- اليمن (Yemen - 11 sources) ---
  {
    name: 'Sabanews Agency',
    nameArabic: 'وكالة الأنباء اليمنية (سبأ)',
    url: 'https://www.sabanews.net',
    feedUrl: 'https://www.sabanews.net/ar/rss.xml',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'اليمن',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 95,
    fetchInterval: 5,
  },
  {
    name: 'Almashhad Alyemeni',
    nameArabic: 'المشهد اليمني',
    url: 'https://www.almashhad-alyemeni.com',
    feedUrl: 'https://www.almashhad-alyemeni.com/rss.xml',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'اليمن',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 90,
    fetchInterval: 5,
  },
  {
    name: 'Aden Al-Ghad',
    nameArabic: 'صحيفة عدن الغد',
    url: 'https://www.adengad.net',
    feedUrl: 'https://www.adengad.net/rss.xml',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'اليمن',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 88,
    fetchInterval: 5,
  },
  {
    name: 'Khuyut Platform',
    nameArabic: 'منصة خيوط الإخبارية',
    url: 'https://www.khuyut.com',
    feedUrl: 'https://www.khuyut.com/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'اليمن',
    language: 'ar',
    category: 'ثقافة',
    type: 'RSS',
    enabled: true,
    priority: 3,
    trustScore: 92,
    fetchInterval: 15,
  },
  {
    name: 'Khabar News Agency',
    nameArabic: 'وكالة خبر للأنباء (اليمن)',
    url: 'https://www.khabaragency.net',
    feedUrl: 'https://www.khabaragency.net/rss.xml',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'اليمن',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 86,
    fetchInterval: 10,
  },
  {
    name: 'Aden Time',
    nameArabic: 'صحيفة عدن تايم',
    url: 'https://www.aden-tm.net',
    feedUrl: 'https://www.aden-tm.net/rss.xml',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'اليمن',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 87,
    fetchInterval: 10,
  },
  {
    name: 'South24 Center',
    nameArabic: 'مركز جنوب 24 للأخبار',
    url: 'https://south24.net',
    feedUrl: 'https://south24.net/news/rss.php',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'اليمن',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 90,
    fetchInterval: 10,
  },
  {
    name: 'Yemen Monitor',
    nameArabic: 'موقع يمن مونيتور',
    url: 'https://www.yemenmonitor.com',
    feedUrl: 'https://www.yemenmonitor.com/feed/',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'اليمن',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 89,
    fetchInterval: 10,
  },
  {
    name: 'Al-Mawqea Post',
    nameArabic: 'الموقع بوست اليمني',
    url: 'https://almawqeapost.net',
    feedUrl: 'https://almawqeapost.net/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'اليمن',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 88,
    fetchInterval: 10,
  },
  {
    name: 'September Net',
    nameArabic: '26 سبتمبر نت',
    url: 'https://www.26sepnews.net',
    feedUrl: 'https://www.26sepnews.net/rss.xml',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'اليمن',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 89,
    fetchInterval: 10,
  },
  {
    name: 'Bawabat Al-Janoub',
    nameArabic: 'بوابة الجنوب الإخبارية',
    url: 'https://www.aljanoub24.com',
    feedUrl: 'https://www.aljanoub24.com/feed',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'اليمن',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 3,
    trustScore: 85,
    fetchInterval: 15,
  },

  // --- السعودية (Saudi Arabia - 10 sources) ---
  {
    name: 'SPA News Agency',
    nameArabic: 'وكالة الأنباء السعودية (SPA)',
    url: 'https://www.spa.gov.sa',
    feedUrl: 'https://www.spa.gov.sa/rss/all.xml',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'السعودية',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 98,
    fetchInterval: 5,
  },
  {
    name: 'Al Riyadh Newspaper',
    nameArabic: 'صحيفة الرياض الرسمية',
    url: 'https://www.alriyadh.com',
    feedUrl: 'https://www.alriyadh.com/section.frontpage.xml',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'السعودية',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 95,
    fetchInterval: 10,
  },
  {
    name: 'Okaz Newspaper',
    nameArabic: 'صحيفة عكاظ',
    url: 'https://www.okaz.com.sa',
    feedUrl: 'https://www.okaz.com.sa/rss/full.xml',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'السعودية',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 92,
    fetchInterval: 10,
  },
  {
    name: 'Sabq Newspaper',
    nameArabic: 'صحيفة سبق الإلكترونية',
    url: 'https://sabq.org',
    feedUrl: 'https://sabq.org/rss/all.xml',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'السعودية',
    language: 'ar',
    category: 'عاجل',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 91,
    fetchInterval: 5,
  },
  {
    name: 'Aleqtisadiah',
    nameArabic: 'صحيفة الاقتصادية السعودية',
    url: 'https://www.aleqt.com',
    feedUrl: 'https://www.aleqt.com/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'السعودية',
    language: 'ar',
    category: 'اقتصاد',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 94,
    fetchInterval: 15,
  },
  {
    name: 'Al Watan Saudi',
    nameArabic: 'صحيفة الوطن السعودية',
    url: 'https://www.alwatan.com.sa',
    feedUrl: 'https://www.alwatan.com.sa/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'السعودية',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 90,
    fetchInterval: 10,
  },
  {
    name: 'Al Madina',
    nameArabic: 'صحيفة المدينة المنورة',
    url: 'https://www.al-madina.com',
    feedUrl: 'https://www.al-madina.com/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'السعودية',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 90,
    fetchInterval: 10,
  },
  {
    name: 'Asharq Al-Awsat',
    nameArabic: 'صحيفة الشرق الأوسط',
    url: 'https://aawsat.com',
    feedUrl: 'https://aawsat.com/rss.xml',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'السعودية',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 96,
    fetchInterval: 5,
  },
  {
    name: 'Argaam Financial',
    nameArabic: 'بوابة أرقام المالية',
    url: 'https://www.argaam.com',
    feedUrl: 'https://www.argaam.com/ar/rss',
    logo: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=100&q=80',
    country: 'السعودية',
    language: 'ar',
    category: 'اقتصاد',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 97,
    fetchInterval: 5,
  },
  {
    name: 'Al-Yaum Newspaper',
    nameArabic: 'صحيفة اليوم السعودية',
    url: 'https://www.alyaum.com',
    feedUrl: 'https://www.alyaum.com/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'السعودية',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 89,
    fetchInterval: 10,
  },

  // --- الإمارات (UAE - 8 sources) ---
  {
    name: 'WAM News Agency',
    nameArabic: 'وكالة أنباء الإمارات (وام)',
    url: 'https://wam.ae',
    feedUrl: 'https://wam.ae/ar/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'الإمارات',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 97,
    fetchInterval: 5,
  },
  {
    name: 'Sky News Arabia',
    nameArabic: 'سكاي نيوز عربية (Sky News Arabia)',
    url: 'https://www.skynewsarabia.com',
    feedUrl: 'https://www.skynewsarabia.com/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'الإمارات',
    language: 'ar',
    category: 'عاجل',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 96,
    fetchInterval: 3,
  },
  {
    name: 'Al Bayan Newspaper',
    nameArabic: 'صحيفة البيان الإماراتية',
    url: 'https://www.albayan.ae',
    feedUrl: 'https://www.albayan.ae/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'الإمارات',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 93,
    fetchInterval: 10,
  },
  {
    name: 'Al Ittihad Abu Dhabi',
    nameArabic: 'صحيفة الاتحاد أبوظبي',
    url: 'https://www.alittihad.ae',
    feedUrl: 'https://www.alittihad.ae/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'الإمارات',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 92,
    fetchInterval: 10,
  },
  {
    name: 'Al Khaleej UAE',
    nameArabic: 'صحيفة الخليج الإماراتية',
    url: 'https://www.alkhaleej.ae',
    feedUrl: 'https://www.alkhaleej.ae/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'الإمارات',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 91,
    fetchInterval: 10,
  },
  {
    name: 'Emarat Al Youm',
    nameArabic: 'صحيفة الإمارات اليوم',
    url: 'https://www.emaratalyoum.com',
    feedUrl: 'https://www.emaratalyoum.com/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'الإمارات',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 90,
    fetchInterval: 10,
  },
  {
    name: 'Al Ain News',
    nameArabic: 'العين الإخبارية',
    url: 'https://al-ain.com',
    feedUrl: 'https://al-ain.com/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'الإمارات',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 91,
    fetchInterval: 5,
  },
  {
    name: 'The National Arabic',
    nameArabic: 'ذا ناشيونال بالعربية',
    url: 'https://www.thenationalnews.com/ar',
    feedUrl: 'https://www.thenationalnews.com/ar/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'الإمارات',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 94,
    fetchInterval: 10,
  },

  // --- قطر (Qatar - 6 sources) ---
  {
    name: 'QNA Qatar Agency',
    nameArabic: 'وكالة الأنباء القطرية (قنا)',
    url: 'https://www.qna.org.qa',
    feedUrl: 'https://www.qna.org.qa/ar/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'قطر',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 96,
    fetchInterval: 5,
  },
  {
    name: 'Al Jazeera Net',
    nameArabic: 'الجزيرة نت (Al Jazeera Arabic)',
    url: 'https://www.aljazeera.net',
    feedUrl: 'https://www.aljazeera.net/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'قطر',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 95,
    fetchInterval: 3,
  },
  {
    name: 'Al Raya Qatar',
    nameArabic: 'صحيفة الراية القطرية',
    url: 'https://www.raya.com',
    feedUrl: 'https://www.raya.com/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'قطر',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 90,
    fetchInterval: 10,
  },
  {
    name: 'Al Arab Qatar',
    nameArabic: 'صحيفة العرب القطرية',
    url: 'https://alarab.qa',
    feedUrl: 'https://alarab.qa/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'قطر',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 89,
    fetchInterval: 10,
  },
  {
    name: 'Al Sharq Qatar',
    nameArabic: 'صحيفة الشرق القطرية',
    url: 'https://al-sharq.com',
    feedUrl: 'https://al-sharq.com/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'قطر',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 89,
    fetchInterval: 10,
  },
  {
    name: 'Al Araby Al Jadeed',
    nameArabic: 'صحيفة العربي الجديد',
    url: 'https://www.alaraby.co.uk',
    feedUrl: 'https://www.alaraby.co.uk/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'قطر',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 93,
    fetchInterval: 5,
  },

  // --- الكويت (Kuwait - 6 sources) ---
  {
    name: 'KUNA Kuwait Agency',
    nameArabic: 'وكالة الأنباء الكويتية (كونا)',
    url: 'https://www.kuna.net.kw',
    feedUrl: 'https://www.kuna.net.kw/NewsRss.aspx?language=ar',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'الكويت',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 96,
    fetchInterval: 5,
  },
  {
    name: 'Al Qabas Kuwait',
    nameArabic: 'صحيفة القبس الكويتية',
    url: 'https://www.alqabas.com',
    feedUrl: 'https://www.alqabas.com/feed',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'الكويت',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 92,
    fetchInterval: 10,
  },
  {
    name: 'Al Rai Kuwait',
    nameArabic: 'جريدة الراي الكويتية',
    url: 'https://www.alraimedia.com',
    feedUrl: 'https://www.alraimedia.com/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'الكويت',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 91,
    fetchInterval: 10,
  },
  {
    name: 'Al Anba Kuwait',
    nameArabic: 'صحيفة الأنبار الكويتية',
    url: 'https://www.alanba.com.kw',
    feedUrl: 'https://www.alanba.com.kw/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'الكويت',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 90,
    fetchInterval: 10,
  },
  {
    name: 'Al Jarida Kuwait',
    nameArabic: 'صحيفة الجريدة الكويتية',
    url: 'https://www.aljarida.com',
    feedUrl: 'https://www.aljarida.com/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'الكويت',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 89,
    fetchInterval: 10,
  },
  {
    name: 'Kuwait Times Arabic',
    nameArabic: 'كويت تايمز بالعربية',
    url: 'https://www.kuwaittimes.com',
    feedUrl: 'https://www.kuwaittimes.com/feed/',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'الكويت',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 88,
    fetchInterval: 15,
  },

  // --- سلطنة عمان والبحرين (Oman & Bahrain - 6 sources) ---
  {
    name: 'ONA Oman Agency',
    nameArabic: 'وكالة الأنباء العمانية (أونا)',
    url: 'https://omannews.gov.om',
    feedUrl: 'https://omannews.gov.om/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'عُمان',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 95,
    fetchInterval: 10,
  },
  {
    name: 'Oman Daily Newspaper',
    nameArabic: 'جريدة عمان اليومية',
    url: 'https://www.omandaily.om',
    feedUrl: 'https://www.omandaily.om/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'عُمان',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 91,
    fetchInterval: 15,
  },
  {
    name: 'Al Shabiba Oman',
    nameArabic: 'صحيفة الشبيبة العمانية',
    url: 'https://www.shabiba.com',
    feedUrl: 'https://www.shabiba.com/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'عُمان',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 90,
    fetchInterval: 15,
  },
  {
    name: 'BNA Bahrain Agency',
    nameArabic: 'وكالة أنباء البحرين (بنا)',
    url: 'https://www.bna.bh',
    feedUrl: 'https://www.bna.bh/ar/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'البحرين',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 94,
    fetchInterval: 10,
  },
  {
    name: 'Al Ayam Bahrain',
    nameArabic: 'صحيفة الأيام البحرينية',
    url: 'https://www.alayam.com',
    feedUrl: 'https://www.alayam.com/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'البحرين',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 90,
    fetchInterval: 15,
  },
  {
    name: 'Akhbar Al Khaleej',
    nameArabic: 'أخبار الخليج البحرينية',
    url: 'https://www.akhbar-alkhaleej.com',
    feedUrl: 'https://www.akhbar-alkhaleej.com/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'البحرين',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 89,
    fetchInterval: 15,
  },

  // --- العراق والأردن وفلسطين ولبنان وسوريا (Iraq, Jordan, Palestine, Lebanon, Syria - 15 sources) ---
  {
    name: 'INA Iraq Agency',
    nameArabic: 'وكالة الأنباء العراقية (واع)',
    url: 'https://www.ina.iq',
    feedUrl: 'https://www.ina.iq/rss.xml',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'العراق',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 94,
    fetchInterval: 5,
  },
  {
    name: 'Shafaq News Iraq',
    nameArabic: 'شفق نيوز العراقية',
    url: 'https://shafaq.com/ar',
    feedUrl: 'https://shafaq.com/ar/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'العراق',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 90,
    fetchInterval: 10,
  },
  {
    name: 'Al Sumaria Iraq',
    nameArabic: 'قناة السومرية الفضائية',
    url: 'https://www.alsumaria.tv',
    feedUrl: 'https://www.alsumaria.tv/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'العراق',
    language: 'ar',
    category: 'عاجل',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 91,
    fetchInterval: 5,
  },
  {
    name: 'Baghdad Today',
    nameArabic: 'بغداد اليوم الإخبارية',
    url: 'https://baghdadtoday.news',
    feedUrl: 'https://baghdadtoday.news/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'العراق',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 88,
    fetchInterval: 10,
  },
  {
    name: 'Petra Jordan Agency',
    nameArabic: 'وكالة الأنباء الأردنية (بترا)',
    url: 'https://petra.gov.jo',
    feedUrl: 'https://petra.gov.jo/Rss/Rss.aspx',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'الأردن',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 95,
    fetchInterval: 5,
  },
  {
    name: 'Al Rai Jordan',
    nameArabic: 'صحيفة الرأي الأردنية',
    url: 'https://alrai.com',
    feedUrl: 'https://alrai.com/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'الأردن',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 92,
    fetchInterval: 10,
  },
  {
    name: 'Ammon News',
    nameArabic: 'وكالة عمون الإخبارية',
    url: 'https://www.ammonnews.net',
    feedUrl: 'https://www.ammonnews.net/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'الأردن',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 90,
    fetchInterval: 10,
  },
  {
    name: 'Wafa Palestine Agency',
    nameArabic: 'وكالة الأنباء والمعلومات الفلسطينية (وفا)',
    url: 'https://www.wafa.ps',
    feedUrl: 'https://www.wafa.ps/ar/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'فلسطين',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 95,
    fetchInterval: 5,
  },
  {
    name: 'Maan News Palestine',
    nameArabic: 'وكالة معاً الإخبارية',
    url: 'https://www.maannews.net',
    feedUrl: 'https://www.maannews.net/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'فلسطين',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 92,
    fetchInterval: 5,
  },
  {
    name: 'Al Quds Newspaper',
    nameArabic: 'جريدة القدس دوت كوم',
    url: 'https://www.alquds.com',
    feedUrl: 'https://www.alquds.com/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'فلسطين',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 90,
    fetchInterval: 10,
  },
  {
    name: 'NNA Lebanon Agency',
    nameArabic: 'الوكالة الوطنية للإعلام اللبنانية',
    url: 'http://nna-leb.gov.lb',
    feedUrl: 'http://nna-leb.gov.lb/ar/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'لبنان',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 94,
    fetchInterval: 5,
  },
  {
    name: 'Annahar Lebanon',
    nameArabic: 'صحيفة النهار اللبنانية',
    url: 'https://www.annahar.com',
    feedUrl: 'https://www.annahar.com/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'لبنان',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 91,
    fetchInterval: 10,
  },
  {
    name: 'LBCI News Lebanon',
    nameArabic: 'المؤسسة اللبنانية للإرسال LBCI',
    url: 'https://www.lbcgroup.tv',
    feedUrl: 'https://www.lbcgroup.tv/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'لبنان',
    language: 'ar',
    category: 'عاجل',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 91,
    fetchInterval: 5,
  },
  {
    name: 'Enab Baladi Syria',
    nameArabic: 'عنب بلدي الإخبارية',
    url: 'https://www.enabbaladi.net',
    feedUrl: 'https://www.enabbaladi.net/feed/',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'سوريا',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 92,
    fetchInterval: 10,
  },
  {
    name: 'Syria TV',
    nameArabic: 'تلفزيون سوريا الإخباري',
    url: 'https://www.syria.tv',
    feedUrl: 'https://www.syria.tv/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'سوريا',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 90,
    fetchInterval: 10,
  },

  // --- مصر وشمال إفريقيا (Egypt, Sudan, Libya, Tunisia, Algeria, Morocco - 20 sources) ---
  {
    name: 'MENA Egypt Agency',
    nameArabic: 'وكالة أنباء الشرق الأوسط (أش أ)',
    url: 'https://www.mena.org.eg',
    feedUrl: 'https://www.mena.org.eg/ar/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'مصر',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 95,
    fetchInterval: 5,
  },
  {
    name: 'Youm7 Egypt',
    nameArabic: 'صحيفة اليوم السابع المصرية',
    url: 'https://www.youm7.com',
    feedUrl: 'https://www.youm7.com/rss/SectionRss?SectionID=203',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'مصر',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 90,
    fetchInterval: 5,
  },
  {
    name: 'Al Ahram Gate',
    nameArabic: 'بوابة الأهرام الرسمية',
    url: 'https://gate.ahram.org.eg',
    feedUrl: 'https://gate.ahram.org.eg/UI/Front/RSS.aspx',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'مصر',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 94,
    fetchInterval: 10,
  },
  {
    name: 'Masrawy Egypt',
    nameArabic: 'موقع مصراوي الإخباري',
    url: 'https://www.masrawy.com',
    feedUrl: 'https://www.masrawy.com/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'مصر',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 89,
    fetchInterval: 10,
  },
  {
    name: 'Shorouk News',
    nameArabic: 'صحيفة الشروق المصرية',
    url: 'https://www.shorouknews.com',
    feedUrl: 'https://www.shorouknews.com/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'مصر',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 91,
    fetchInterval: 10,
  },
  {
    name: 'Al Masry Al Youm',
    nameArabic: 'صحيفة المصري اليوم',
    url: 'https://www.almasryalyoum.com',
    feedUrl: 'https://www.almasryalyoum.com/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'مصر',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 92,
    fetchInterval: 10,
  },
  {
    name: 'SUNA Sudan Agency',
    nameArabic: 'وكالة السودان للأنباء (سونا)',
    url: 'https://suna-news.net',
    feedUrl: 'https://suna-news.net/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'السودان',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 93,
    fetchInterval: 10,
  },
  {
    name: 'Sudan Tribune',
    nameArabic: 'سودان تربيون الإخبارية',
    url: 'https://sudantribune.com/ar',
    feedUrl: 'https://sudantribune.com/ar/feed/',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'السودان',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 90,
    fetchInterval: 10,
  },
  {
    name: 'LANA Libya Agency',
    nameArabic: 'وكالة الأنباء الليبية (وال)',
    url: 'https://lana.gov.ly',
    feedUrl: 'https://lana.gov.ly/ar/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'ليبيا',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 91,
    fetchInterval: 10,
  },
  {
    name: 'Al Wasat Libya',
    nameArabic: 'بوابة الوسط الليبية',
    url: 'http://alwasat.ly',
    feedUrl: 'http://alwasat.ly/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'ليبيا',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 89,
    fetchInterval: 10,
  },
  {
    name: 'TAP Tunisia Agency',
    nameArabic: 'وكالة تونس إفريقيا للأنباء (وات)',
    url: 'https://www.tap.info.tn',
    feedUrl: 'https://www.tap.info.tn/ar/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'تونس',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 94,
    fetchInterval: 10,
  },
  {
    name: 'Nessma News Tunisia',
    nameArabic: 'قناة نسمة تونس',
    url: 'https://www.nessma.tv',
    feedUrl: 'https://www.nessma.tv/ar/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'تونس',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 88,
    fetchInterval: 10,
  },
  {
    name: 'APS Algeria Agency',
    nameArabic: 'وكالة الأنباء الجزائرية (واج)',
    url: 'https://www.aps.dz/ar',
    feedUrl: 'https://www.aps.dz/ar/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'الجزائر',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 95,
    fetchInterval: 10,
  },
  {
    name: 'El Khabar Algeria',
    nameArabic: 'صحيفة الخبر الجزائرية',
    url: 'https://www.elkhabar.com',
    feedUrl: 'https://www.elkhabar.com/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'الجزائر',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 91,
    fetchInterval: 10,
  },
  {
    name: 'Ennahar Online Algeria',
    nameArabic: 'النهار أونلاين الجزائر',
    url: 'https://www.ennaharonline.com',
    feedUrl: 'https://www.ennaharonline.com/feed/',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'الجزائر',
    language: 'ar',
    category: 'عاجل',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 90,
    fetchInterval: 5,
  },
  {
    name: 'MAP Morocco Agency',
    nameArabic: 'وكالة المغرب العربي للأنباء (ومع)',
    url: 'https://www.mapnews.ma',
    feedUrl: 'https://www.mapnews.ma/ar/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'المغرب',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 95,
    fetchInterval: 10,
  },
  {
    name: 'Hespress Morocco',
    nameArabic: 'جريدة هسبريس الإلكترونية',
    url: 'https://www.hespress.com',
    feedUrl: 'https://www.hespress.com/feed',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'المغرب',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 92,
    fetchInterval: 5,
  },
  {
    name: 'Le360 Morocco',
    nameArabic: 'موقع 360 المغربي',
    url: 'https://ar.le360.ma',
    feedUrl: 'https://ar.le360.ma/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'المغرب',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 90,
    fetchInterval: 10,
  },
  {
    name: 'AMI Mauritania Agency',
    nameArabic: 'الوكالة الموريتانية للأنباء (وما)',
    url: 'https://ami.mr',
    feedUrl: 'https://ami.mr/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'موريتانيا',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 91,
    fetchInterval: 15,
  },
  {
    name: 'SONNA Somalia Agency',
    nameArabic: 'وكالة الأنباء الوطنية الصومالية (صونا)',
    url: 'https://sonna.so/ar',
    feedUrl: 'https://sonna.so/ar/feed/',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'الصومال',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 90,
    fetchInterval: 15,
  },

  // --- المصادر العالمية بالعربية (Global Agencies - 15 sources) ---
  {
    name: 'BBC Arabic',
    nameArabic: 'بي بي سي عربي (BBC)',
    url: 'https://www.bbc.com/arabic',
    feedUrl: 'https://feeds.bbci.co.uk/arabic/rss.xml',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'عالمي',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 97,
    fetchInterval: 3,
  },
  {
    name: 'France24 Arabic',
    nameArabic: 'فرانس 24 بالعربية (France24)',
    url: 'https://www.france24.com/ar',
    feedUrl: 'https://www.france24.com/ar/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'عالمي',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 96,
    fetchInterval: 5,
  },
  {
    name: 'RT Arabic',
    nameArabic: 'روسيا اليوم (RT Arabic)',
    url: 'https://arabic.rt.com',
    feedUrl: 'https://arabic.rt.com/rss/',
    logo: 'https://arabic.rt.com/static/img/logo_rt/logorss.gif',
    country: 'عالمي',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 91,
    fetchInterval: 5,
  },
  {
    name: 'DW Arabic',
    nameArabic: 'دويتشه فيله عربية (DW)',
    url: 'https://www.dw.com/ar',
    feedUrl: 'https://rss.dw.com/xml/rss-ar-all',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'عالمي',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 95,
    fetchInterval: 10,
  },
  {
    name: 'CNN Arabic',
    nameArabic: 'سي إن إن بالعربية (CNN Arabic)',
    url: 'https://arabic.cnn.com',
    feedUrl: 'https://arabic.cnn.com/rss/cnnarabic_world.rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'عالمي',
    language: 'ar',
    category: 'عاجل',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 96,
    fetchInterval: 5,
  },
  {
    name: 'Al Arabiya News',
    nameArabic: 'قناة العربية الإخبارية',
    url: 'https://www.alarabiya.net',
    feedUrl: 'https://www.alarabiya.net/tools/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'عالمي',
    language: 'ar',
    category: 'عاجل',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 96,
    fetchInterval: 3,
  },
  {
    name: 'Al Hadath Channel',
    nameArabic: 'قناة الحدث الإخبارية',
    url: 'https://www.alhadath.net',
    feedUrl: 'https://www.alhadath.net/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'عالمي',
    language: 'ar',
    category: 'عاجل',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 96,
    fetchInterval: 3,
  },
  {
    name: 'TRT Arabic',
    nameArabic: 'تي آر تي عربي (TRT)',
    url: 'https://www.trtarabi.com',
    feedUrl: 'https://www.trtarabi.com/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'عالمي',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 92,
    fetchInterval: 10,
  },
  {
    name: 'Independent Arabia',
    nameArabic: 'اندبندنت عربية',
    url: 'https://www.independentarabia.com',
    feedUrl: 'https://www.independentarabia.com/rss.xml',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'عالمي',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 95,
    fetchInterval: 10,
  },
  {
    name: 'Euronews Arabic',
    nameArabic: 'يورونيوز بالعربية',
    url: 'https://arabic.euronews.com',
    feedUrl: 'https://arabic.euronews.com/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'عالمي',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 93,
    fetchInterval: 10,
  },
  {
    name: 'Anadolu Agency Arabic',
    nameArabic: 'وكالة الأناضول بالعربية',
    url: 'https://www.aa.com.tr/ar',
    feedUrl: 'https://www.aa.com.tr/ar/rss/default.xml',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'عالمي',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 94,
    fetchInterval: 5,
  },
  {
    name: 'Reuters Arabic News',
    nameArabic: 'رويترز بالعربية',
    url: 'https://www.reuters.com',
    feedUrl: 'https://www.reuters.com/arc/outboundfeeds/rss/?outputType=xml',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'عالمي',
    language: 'ar',
    category: 'اقتصاد',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 98,
    fetchInterval: 5,
  },
  {
    name: 'Sputnik Arabic',
    nameArabic: 'سبوتنيك بالعربية',
    url: 'https://sputnikarabic.ae',
    feedUrl: 'https://sputnikarabic.ae/export/rss2/archive/index.xml',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'عالمي',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 89,
    fetchInterval: 10,
  },
  {
    name: 'CGTN Arabic',
    nameArabic: 'شبكة تلفزيون الصين بالعربية (CGTN)',
    url: 'https://arabic.cgtn.com',
    feedUrl: 'https://arabic.cgtn.com/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'عالمي',
    language: 'ar',
    category: 'أخبار عامة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 91,
    fetchInterval: 15,
  },
  {
    name: 'Al-Hurra News',
    nameArabic: 'قناة الحرة الإخبارية',
    url: 'https://www.alhurra.com',
    feedUrl: 'https://www.alhurra.com/rss',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=100&q=80',
    country: 'عالمي',
    language: 'ar',
    category: 'سياسة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 94,
    fetchInterval: 5,
  },

  // --- تقنية واقتصاد ورياضة وعلوم (Tech, Economy, Sports, Health, Energy - 15 sources) ---
  {
    name: 'AITNews Tech',
    nameArabic: 'البوابة العربية للأخبار التقنية',
    url: 'https://aitnews.com',
    feedUrl: 'https://aitnews.com/feed/',
    logo: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=100&q=80',
    country: 'عالمي',
    language: 'ar',
    category: 'تقنية',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 95,
    fetchInterval: 10,
  },
  {
    name: 'Tech-WD',
    nameArabic: 'موقع عالم التقنية',
    url: 'https://www.tech-wd.com',
    feedUrl: 'https://www.tech-wd.com/wd/feed/',
    logo: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=100&q=80',
    country: 'السعودية',
    language: 'ar',
    category: 'تقنية',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 92,
    fetchInterval: 15,
  },
  {
    name: 'CNBC Arabia',
    nameArabic: 'سي إن بي سي عربية (CNBC Arabia)',
    url: 'https://www.cnbcarabia.com',
    feedUrl: 'https://www.cnbcarabia.com/rss.xml',
    logo: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=100&q=80',
    country: 'الإمارات',
    language: 'ar',
    category: 'اقتصاد',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 97,
    fetchInterval: 5,
  },
  {
    name: 'Asharq Business Bloomberg',
    nameArabic: 'اقتصاد الشرق مع بلومبرغ',
    url: 'https://www.asharqbusiness.com',
    feedUrl: 'https://www.asharqbusiness.com/rss',
    logo: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=100&q=80',
    country: 'السعودية',
    language: 'ar',
    category: 'اقتصاد',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 97,
    fetchInterval: 5,
  },
  {
    name: 'Kooora Press',
    nameArabic: 'موقع كووورة الرياضي الأول',
    url: 'https://www.kooora.com',
    feedUrl: 'https://www.kooora.com/rss.aspx',
    logo: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=100&q=80',
    country: 'عالمي',
    language: 'ar',
    category: 'رياضة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 94,
    fetchInterval: 5,
  },
  {
    name: 'YallaKora Sports',
    nameArabic: 'موقع يلا كورة الرياضي',
    url: 'https://www.yallakora.com',
    feedUrl: 'https://www.yallakora.com/rss',
    logo: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=100&q=80',
    country: 'مصر',
    language: 'ar',
    category: 'رياضة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 90,
    fetchInterval: 10,
  },
  {
    name: 'FilGoal Sports',
    nameArabic: 'موقع في الجول الرياضي',
    url: 'https://www.filgoal.com',
    feedUrl: 'https://www.filgoal.com/rss',
    logo: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=100&q=80',
    country: 'مصر',
    language: 'ar',
    category: 'رياضة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 91,
    fetchInterval: 10,
  },
  {
    name: 'beIN Sports Arabic',
    nameArabic: 'بي إن سبورتس بالعربية',
    url: 'https://www.beinsports.com/ar-mena',
    feedUrl: 'https://www.beinsports.com/ar-mena/rss',
    logo: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=100&q=80',
    country: 'قطر',
    language: 'ar',
    category: 'رياضة',
    type: 'RSS',
    enabled: true,
    priority: 1,
    trustScore: 96,
    fetchInterval: 5,
  },
  {
    name: 'Hesport Morocco',
    nameArabic: 'هسبورت الرياضية المغربية',
    url: 'https://www.hesport.com',
    feedUrl: 'https://www.hesport.com/feed',
    logo: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=100&q=80',
    country: 'المغرب',
    language: 'ar',
    category: 'رياضة',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 90,
    fetchInterval: 10,
  },
  {
    name: 'Mubasher Economic',
    nameArabic: 'معلومات مباشر الاقتصادية',
    url: 'https://www.mubasher.info',
    feedUrl: 'https://www.mubasher.info/rss',
    logo: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=100&q=80',
    country: 'السعودية',
    language: 'ar',
    category: 'اقتصاد',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 93,
    fetchInterval: 10,
  },
  {
    name: 'Unlimit-Tech',
    nameArabic: 'موقع التقنية بلا حدود',
    url: 'https://www.unlimit-tech.com',
    feedUrl: 'https://www.unlimit-tech.com/feed/',
    logo: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=100&q=80',
    country: 'السعودية',
    language: 'ar',
    category: 'تقنية',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 90,
    fetchInterval: 15,
  },
  {
    name: 'SciDev.Net Arabic',
    nameArabic: 'شبكة العلوم والتنمية بالعربية',
    url: 'https://www.scidev.net/mena',
    feedUrl: 'https://www.scidev.net/mena/rss/',
    logo: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=100&q=80',
    country: 'عالمي',
    language: 'ar',
    category: 'علوم',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 94,
    fetchInterval: 30,
  },
  {
    name: 'Sayidaty Magazine',
    nameArabic: 'مجلة سيدتي الاجتماعية',
    url: 'https://www.sayidaty.net',
    feedUrl: 'https://www.sayidaty.net/rss.xml',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'السعودية',
    language: 'ar',
    category: 'منوعات',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 90,
    fetchInterval: 20,
  },
  {
    name: 'Kul Al Usra',
    nameArabic: 'مجلة كل الأسرة',
    url: 'https://kulalusra.ae',
    feedUrl: 'https://kulalusra.ae/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'الإمارات',
    language: 'ar',
    category: 'منوعات',
    type: 'RSS',
    enabled: true,
    priority: 3,
    trustScore: 88,
    fetchInterval: 30,
  },
  {
    name: 'Weather Arabia',
    nameArabic: 'طقس العرب (ArabiaWeather)',
    url: 'https://www.arabiaweather.com',
    feedUrl: 'https://www.arabiaweather.com/ar/rss',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=100&q=80',
    country: 'الأردن',
    language: 'ar',
    category: 'طقس',
    type: 'RSS',
    enabled: true,
    priority: 2,
    trustScore: 93,
    fetchInterval: 15,
  },
];
