export const INITIAL_PRODUCTION_ARTICLES = [
  {
    title: 'النفط يهبط بفعل مؤشرات على سياسة الاتحادي وشائعات عن اتفاق بشأن مضيق هرمز',
    slug: 'oil-prices-decline-fed-policy-hormuz-strait',
    category: 'اقتصاد',
    country: 'السعودية',
    summary: 'تراجعت أسعار النفط العالمية في تعاملات اليوم وسط ترقب لقرارات الفيدرالي الأمريكي وتقارير عن استقرار حركة الملاحة في مضيق هرمز.',
    content: 'تراجعت أسعار النفط العالمية اليوم الجمعة متأثرة ببيانات اقتصادية أمريكية وتوقعات تشديد السياسة النقدية من جانب مجلس الاحتياطي الاتحادي. وساهمت مؤشرات استقرار حركة الشحن والملاحة في الممرات المائية الحيوية ومنها مضيق هرمز في تهدئة مخاوف نقص الإمدادات في الأسواق العالمية.',
    coverImageUrl: 'https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?auto=format&fit=crop&w=1200&q=80',
    sourceName: 'صحيفة الاقتصادية',
    author: 'فريق الاقتصاد',
    contentStatus: 'full',
    contentClassification: 'FULL_PERMITTED_CONTENT',
    readingTimeMinutes: 3,
    isBreaking: false,
    isTrending: true,
    publishedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    title: 'وارش: التضخم لا يتباطأ.. ونتعهد بإعادته إلى مستهدف الفيدرالي البالغ 2%',
    slug: 'warsh-inflation-not-slowing-fed-target-commitment',
    category: 'اقتصاد',
    country: 'عالمي',
    summary: 'أكد عضو مجلس محافظي الفيدرالي السابق أن معدلات التضخم لا تزال تتطلب إجراءات حاسمة للوصول إلى المستهدف الرسمي البالغ 2%.',
    content: 'صرح كيفين وارش بأن الضغوط التضخمية في الاقتصاد الأمريكي لم تشهد التباطؤ الكافي بعد، مشدداً على التزام البنك المركزي بتبني سياسات نقدية تضمن عودة التضخم إلى المستهدف المستدام عند 2 بالمائة على المدى المتوسط دون الإضرار بالنمو.',
    coverImageUrl: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=1200&q=80',
    sourceName: 'صحيفة الاقتصادية',
    author: 'وكالات أنباء',
    contentStatus: 'full',
    contentClassification: 'FULL_PERMITTED_CONTENT',
    readingTimeMinutes: 4,
    isBreaking: true,
    isTrending: true,
    publishedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    title: 'شات جي بي تي يتيح تصميم ملصقات مخصصة ومشاركتها مباشرة على واتساب',
    slug: 'chatgpt-custom-stickers-whatsapp-integration',
    category: 'تقنية',
    country: 'عالمي',
    summary: 'أعلنت OpenAI عن ميزة جديدة تتيح للمستخدمين توليد ملصقات مخصصة بالذكاء الاصطناعي وتصديرها مباشرة إلى تطبيق واتساب.',
    content: 'أطلقت شركة OpenAI ميزة تفاعلية جديدة تدمج أدوات توليد الصور مع تطبيقات المراسلة الفورية، حيث بات بإمكان مستخدمي ChatGPT إنشاء وتصميم ملصقات مخصصة بالذكاء الاصطناعي ومشاركتها فوراً عبر تطبيق واتساب بدقة عالية وتنسيقات شفافة.',
    coverImageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    sourceName: 'البوابة العربية للأخبار التقنية',
    author: 'محرر التقنية',
    contentStatus: 'full',
    contentClassification: 'FULL_PERMITTED_CONTENT',
    readingTimeMinutes: 2,
    isBreaking: false,
    isTrending: true,
    publishedAt: new Date(Date.now() - 3600000 * 6).toISOString(),
  },
  {
    title: 'الريال السعودي يحافظ على استقراره أمام العملات الرئيسية في تداولات الصباح',
    slug: 'saudi-riyal-maintains-stability-foreign-currencies',
    category: 'اقتصاد',
    country: 'السعودية',
    summary: 'سجل الريال السعودي استقراراً ملحوظاً مقابل الدولار الأمريكي وسلة العملات الدولية في تعاملات البنوك والأسواق المالية.',
    content: 'أظهرت بيانات البنك المركزي السعودي استمرار استقرار سعر صرف الريال أمام الدولار الأمريكي مدعوماً بالاحتياطيات الأجنبية القوية والسياسة النقدية المتوازنة التي تدعم استقرار الأسواق المحلية والتدفقات الاستثمارية.',
    coverImageUrl: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&w=1200&q=80',
    sourceName: 'صحيفة الرياض',
    author: 'القسم الاقتصادي',
    contentStatus: 'full',
    contentClassification: 'FULL_PERMITTED_CONTENT',
    readingTimeMinutes: 2,
    isBreaking: false,
    isTrending: false,
    publishedAt: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    title: 'انطلاق فعاليات معرض الذكاء الاصطناعي للشركات الناشئة في الشرق الأوسط',
    slug: 'ai-startup-expo-middle-east-launch',
    category: 'تقنية',
    country: 'الإمارات',
    summary: 'شهدت فعاليات قمة الذكاء الاصطناعي مشاركة مئات الشركات الناشئة لعرض أحدث الحلول البرمجية ونماذج التعلم العميق.',
    content: 'افتتحت اليوم أعمال المعرض الإقليمي للذكاء الاصطناعي بمشاركة واسعة من رواد الأعمال والمستثمرين، حيث تم استعراض أحدث الابتكارات في مجالات معالجة اللغات الطبيعية، الروبوتات الذكية، وحلول الحوسبة السحابية المتطورة للشركات والمؤسسات.',
    coverImageUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=1200&q=80',
    sourceName: 'العربية نت',
    author: 'فريق التغطيات',
    contentStatus: 'full',
    contentClassification: 'FULL_PERMITTED_CONTENT',
    readingTimeMinutes: 3,
    isBreaking: false,
    isTrending: true,
    publishedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
  }
];
